# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'character_trainer_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(16, 9, 771, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.Options = QtWidgets.QWidget()
        self.Options.setObjectName("Options")
        self.tabWidget.addTab(self.Options, "")
        self.Table = QtWidgets.QWidget()
        self.Table.setObjectName("Table")
        self.tableWidget = QtWidgets.QTableWidget(self.Table)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 741, 491))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.Table, "")
        self.Graph = QtWidgets.QWidget()
        self.Graph.setObjectName("Graph")
        self.tabWidget.addTab(self.Graph, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Options), _translate("MainWindow", "Options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Table), _translate("MainWindow", "Results Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Graph), _translate("MainWindow", "Results Graph"))
